# -*- coding: utf-8 -*-
# 品牌/分类定义 与 分类1-6 商品数据（三语）
# 字段: b=品牌序号 m=型号 t=类型三语 s=规格(语言无关) f=卖点三语
#       price/orig=CNY分 tags=搜索标签 flash=秒杀 img=图片关键词 lock=图源锁

BRANDS = [
    ("Nebula", "星尘", "星塵"), ("Aurora", "极光", "極光"),
    ("Skylark", "云雀", "雲雀"), ("Baize", "白泽", "白澤"),
    ("Mistral", "岚风", "嵐風"), ("Obsidian", "曜石", "曜石"),
    ("Lumi", "拾光", "拾光"), ("Sailon", "千帆", "千帆"),
    ("Volta", "伏特", "伏特"), ("Kestrel", "红隼", "紅隼"),
    ("Camellia", "山茶", "山茶"), ("Velvet", "绒言", "絨言"),
    ("Mousse", "慕斯", "慕斯"), ("Tide", "潮汐", "潮汐"),
    ("Ember", "燃点", "燃點"), ("Sprout", "芽绿", "芽綠"),
    ("Pinecone", "松果", "松果"), ("Glacier", "冰川", "冰川"),
    ("Moonview", "月见", "月見"), ("Anvil", "铁砧", "鐵砧"),
    ("Wildpath", "野径", "野徑"), ("Frosting", "糖霜", "糖霜"),
    ("Bamboo", "竹语", "竹語"), ("Deepblue", "深蓝", "深藍"),
    ("Dewdrop", "晨露", "晨露"), ("Jelly", "果冻", "果凍"),
    ("Whaletalk", "鲸语", "鯨語"), ("Marigold", "金盏", "金盞"),
    ("OrchardTalk", "果园说", "果園說"), ("GrainRain", "谷雨", "穀雨"),
    ("FreshEdge", "鲜锋", "鮮鋒"), ("TasteHill", "味觉山", "味覺山"),
    ("WeaveHome", "织家", "織家"), ("ClearZone", "净界", "淨界"),
    ("StrideFit", "步履", "步履"), ("PeakGo", "峰行", "峰行"),
    ("TinyBud", "童萌", "童萌"), ("JoyBrick", "乐拼", "樂拼"),
    ("PageRiver", "页川", "頁川"), ("GlyphSpace", "字间", "字間"),
    ("PawPrint", "爪印", "爪印"), ("MeowPaw", "喵汪", "喵汪"),
]

CATEGORIES = [
    dict(id=1, slug="digital", emoji="📱", sortOrder=1,
         name={"en": "Phones & Digital", "zhHans": "手机数码", "zhHant": "手機數碼"}),
    dict(id=2, slug="computers", emoji="💻", sortOrder=2,
         name={"en": "Computers & Office", "zhHans": "电脑办公", "zhHant": "電腦辦公"}),
    dict(id=3, slug="appliances", emoji="🔌", sortOrder=3,
         name={"en": "Home Appliances", "zhHans": "家用电器", "zhHant": "家用電器"}),
    dict(id=4, slug="audio", emoji="🎧", sortOrder=4,
         name={"en": "Audio & Video", "zhHans": "耳机影音", "zhHant": "耳機影音"}),
    dict(id=5, slug="fashion", emoji="👗", sortOrder=5,
         name={"en": "Fashion", "zhHans": "服饰鞋包", "zhHant": "服飾鞋包"}),
    dict(id=6, slug="beauty", emoji="💄", sortOrder=6,
         name={"en": "Beauty & Care", "zhHans": "美妆个护", "zhHant": "美妝個護"}),
    dict(id=7, slug="grocery", emoji="🍱", sortOrder=7,
         name={"en": "Grocery & Fresh", "zhHans": "食品生鲜", "zhHant": "食品生鮮"}),
    dict(id=8, slug="living", emoji="🛋️", sortOrder=8,
         name={"en": "Home & Living", "zhHans": "家居日用", "zhHant": "家居日用"}),
    dict(id=9, slug="sports", emoji="🏀", sortOrder=9,
         name={"en": "Sports & Outdoor", "zhHans": "运动户外", "zhHant": "運動戶外"}),
    dict(id=10, slug="baby", emoji="🧸", sortOrder=10,
         name={"en": "Baby & Toys", "zhHans": "母婴玩具", "zhHant": "母嬰玩具"}),
    dict(id=11, slug="books", emoji="📚", sortOrder=11,
         name={"en": "Books & Fun", "zhHans": "图书文娱", "zhHant": "圖書文娛"}),
    dict(id=12, slug="pet", emoji="🐾", sortOrder=12,
         name={"en": "Pet Life", "zhHans": "宠物生活", "zhHant": "寵物生活"}),
]


def P(b, m, t, s, f, price, orig, tags, img, flash=False, stock=None, sales=None, rating=None):
    return dict(b=b, m=m, t=t, s=s, f=f, price=price, orig=orig, tags=tags,
                img=img, flash=flash, stock=stock, sales=sales, rating=rating)


PRODUCTS_A = {
    1: [  # 手机数码
        P(0, "X5 Pro", {"en": "Flagship Smartphone", "zhHans": "旗舰手机", "zhHant": "旗艦手機"}, "512GB",
          {"en": "Next-gen chip with 120Hz LTPO display and 100W fast charge.",
           "zhHans": "新一代旗舰芯片，120Hz LTPO 护眼屏，100W 快充。",
           "zhHant": "新一代旗艦晶片，120Hz LTPO 護眼螢幕，100W 快充。"},
          459900, 529900, ["flagship", "5g", "amoled"], "smartphone", flash=True),
        P(0, "X5", {"en": "Flagship Smartphone", "zhHans": "旗舰手机", "zhHant": "旗艦手機"}, "256GB",
          {"en": "Same flagship core, lighter on the wallet.",
           "zhHans": "同款旗舰核心，价格更亲民。",
           "zhHant": "同款旗艦核心，價格更親民。"},
          359900, 399900, ["flagship", "5g"], "smartphone"),
        P(1, "Fold S", {"en": "Foldable Phone", "zhHans": "折叠屏手机", "zhHant": "摺疊螢幕手機"}, "512GB",
          {"en": "8-inch inner screen folds into a pocketable body.",
           "zhHans": "8 英寸内屏，折叠后轻松入袋。",
           "zhHant": "8 吋內螢幕，摺疊後輕鬆入袋。"},
          799900, 899900, ["foldable", "5g"], "smartphone"),
        P(3, "Neo 9", {"en": "Performance Phone", "zhHans": "性能手机", "zhHant": "性能手機"}, "256GB",
          {"en": "Gaming-grade cooling keeps frame rates flat.",
           "zhHans": "电竞级散热，帧率稳如直线。",
           "zhHant": "電競級散熱，幀率穩如直線。"},
          259900, 299900, ["gaming", "5g"], "smartphone", flash=True),
        P(4, "Lite 5G", {"en": "Budget Smartphone", "zhHans": "5G 千元机", "zhHant": "5G 千元機"}, "128GB",
          {"en": "5G and a big battery under ¥1,500.",
           "zhHans": "千元档也有 5G 和大电池。",
           "zhHant": "千元檔也有 5G 和大電池。"},
          129900, 149900, ["budget", "5g"], "smartphone"),
        P(5, "UltraCam 200", {"en": "Camera Phone", "zhHans": "影像手机", "zhHant": "影像手機"}, "1TB",
          {"en": "1-inch sensor and 200MP periscope zoom.",
           "zhHans": "一英寸大底，200MP 潜望长焦。",
           "zhHant": "一吋大底，200MP 潛望長焦。"},
          669900, 729900, ["camera", "flagship"], "smartphone"),
        P(2, "Tab Air", {"en": "Tablet", "zhHans": "平板电脑", "zhHant": "平板電腦"}, "11英寸 256GB",
          {"en": "2.8K 144Hz screen, great for notes and streaming.",
           "zhHans": "2.8K 144Hz 好屏，笔记追剧两相宜。",
           "zhHant": "2.8K 144Hz 好好螢幕，筆記追劇兩相宜。"},
          199900, 239900, ["tablet", "stylus"], "tablet"),
        P(2, "Tab Pro", {"en": "Tablet", "zhHans": "平板电脑", "zhHant": "平板電腦"}, "12.6英寸 512GB",
          {"en": "Desktop-class chip handles light editing on the go.",
           "zhHans": "桌面级芯片，随身轻办公。",
           "zhHant": "桌面級晶片，隨身輕辦公。"},
          349900, 389900, ["tablet", "productivity"], "tablet"),
        P(6, "Watch C3", {"en": "Smartwatch", "zhHans": "智能手表", "zhHant": "智慧手錶"}, "",
          {"en": "14-day battery with full health tracking.",
           "zhHans": "14 天长续航，健康监测全都有。",
           "zhHant": "14 天長續航，健康監測全都有。"},
          89900, 109900, ["smartwatch", "health"], "smartwatch", flash=True),
        P(6, "Band 9", {"en": "Fitness Band", "zhHans": "智能手环", "zhHant": "智慧手環"}, "",
          {"en": "Lightweight tracker for sleep, steps and SpO2.",
           "zhHans": "轻若无物，睡眠步数血氧都记录。",
           "zhHant": "輕若無物，睡眠步數血氧都記錄。"},
          24900, 29900, ["band", "fitness"], "smartwatch"),
        P(7, "Cam M2", {"en": "Mirrorless Camera", "zhHans": "微单相机", "zhHant": "微單相機"}, "APS-C 双镜头",
          {"en": "Flip screen and eye-AF for vlog starters.",
           "zhHans": "翻转屏+眼部对焦，Vlog 入门首选。",
           "zhHant": "翻轉螢幕+眼部對焦，Vlog 入門首選。"},
          489900, 559900, ["camera", "vlog"], "camera"),
        P(7, "Cam Pocket", {"en": "Compact Camera", "zhHans": "卡片相机", "zhHant": "卡片相機"}, "",
          {"en": "Pocketable retro body, one-button shooting.",
           "zhHans": "复古小巧机身，一键直出氛围感。",
           "zhHant": "復古小巧機身，一鍵直出氛圍感。"},
          159900, 189900, ["camera", "retro"], "camera"),
        P(8, "Fly One", {"en": "Entry Drone", "zhHans": "入门无人机", "zhHant": "入門無人機"}, "",
          {"en": "GPS return-to-home and 31-min flight time.",
           "zhHans": "GPS 一键返航，31 分钟续航。",
           "zhHant": "GPS 一鍵返航，31 分鐘續航。"},
          169900, 199900, ["drone", "gps"], "drone"),
        P(8, "Fly Mini", {"en": "Mini Drone", "zhHans": "迷你无人机", "zhHant": "迷你無人機"}, "",
          {"en": "Under 249g, no registration needed in most regions.",
           "zhHans": "249g 以内，多数地区免登记。",
           "zhHant": "249g 以內，多數地區免登記。"},
          229900, 259900, ["drone", "mini"], "drone"),
        P(9, "Charge 20K", {"en": "Power Bank", "zhHans": "充电宝", "zhHant": "行動電源"}, "20000mAh 65W",
          {"en": "Charges your laptop, airline-safe capacity.",
           "zhHans": "能给笔记本充电，可带上飞机。",
           "zhHant": "能給筆電充電，可帶上飛機。"},
          19900, 25900, ["powerbank", "fastcharge"], "powerbank"),
        P(9, "GaN Trio", {"en": "GaN Charger", "zhHans": "氮化镓充电器", "zhHant": "氮化鎵充電器"}, "65W 三口",
          {"en": "One brick for phone, tablet and laptop.",
           "zhHans": "一个头搞定手机平板笔记本。",
           "zhHant": "一個頭搞分手機平板筆電。"},
          12900, 16900, ["charger", "gan"], "powerbank"),
        P(10, "Drive 4K", {"en": "Dash Cam", "zhHans": "行车记录仪", "zhHant": "行車記錄器"}, "",
          {"en": "4K night vision with parking guard.",
           "zhHans": "4K 夜视，停车监控全时守护。",
           "zhHant": "4K 夜視，停車監控全時守護。"},
          39900, 49900, ["dashcam", "car"], "camera"),
        P(11, "Reader 7", {"en": "E-reader", "zhHans": "电子书阅读器", "zhHant": "電子書閱讀器"}, "7英寸",
          {"en": "Warm-light e-ink, weeks of reading per charge.",
           "zhHans": "暖光墨水屏，一次充电读数周。",
           "zhHant": "暖光墨水屏，一次充電讀數週。"},
          89900, 99900, ["ereader", "ink"], "tablet"),
    ],
    2: [  # 电脑办公
        P(4, "Book 14", {"en": "Ultrabook", "zhHans": "轻薄笔记本", "zhHant": "輕薄筆電"}, "14英寸 32GB",
          {"en": "1.19kg magnesium body, all-day 18h battery.",
           "zhHans": "1.19kg 镁合金机身，18 小时全天续航。",
           "zhHant": "1.19kg 鎂合金機身，18 小時全天續航。"},
          569900, 629900, ["laptop", "ultrabook"], "laptop"),
        P(5, "Rig 16", {"en": "Gaming Laptop", "zhHans": "游戏本", "zhHant": "遊戲本"}, "16英寸 RTX级",
          {"en": "240Hz panel with vapor-chamber cooling.",
           "zhHans": "240Hz 高刷屏+均热板散热。",
           "zhHant": "240Hz 高更新率螢幕+均熱板散熱。"},
          869900, 969900, ["laptop", "gaming"], "laptop", flash=True),
        P(12, "Desk Mini", {"en": "Mini PC", "zhHans": "迷你主机", "zhHant": "迷你主機"}, "",
          {"en": "Palm-sized desktop that drives triple 4K displays.",
           "zhHans": "巴掌大的主机，点亮三块 4K 屏。",
           "zhHant": "巴掌大的主機，點亮三塊 4K 螢幕。"},
          279900, 319900, ["minipc", "desktop"], "computer"),
        P(12, "Office All-in-One", {"en": "All-in-One PC", "zhHans": "一体机", "zhHant": "一體機"}, "27英寸",
          {"en": "Clean desk setup with pop-up webcam.",
           "zhHans": "隐藏式摄像头，桌面一步清爽。",
           "zhHant": "隱藏式鏡頭，桌面一步清爽。"},
          469900, 529900, ["aio", "desktop"], "computer"),
        P(13, "Mech K87", {"en": "Mechanical Keyboard", "zhHans": "机械键盘", "zhHant": "機械鍵盤"}, "87键 Gasket",
          {"en": "Hot-swap switches, gasket mount, creamy sound.",
           "zhHans": "热插拔轴体+Gasket 结构，手感声音双在线。",
           "zhHant": "熱插拔軸體+Gasket 結構，手感聲音雙在線。"},
          39900, 49900, ["keyboard", "mechanical"], "keyboard", flash=True),
        P(13, "Slim K1", {"en": "Keyboard", "zhHans": "薄膜键盘", "zhHant": "薄膜鍵盤"}, "",
          {"en": "Whisper-quiet scissor keys for the office.",
           "zhHans": "剪刀脚静音结构，办公不扰邻。",
           "zhHant": "剪刀腳靜音結構，辦公不擾鄰。"},
          12900, 15900, ["keyboard", "quiet"], "keyboard"),
        P(14, "Glide Pro", {"en": "Wireless Mouse", "zhHans": "无线鼠标", "zhHant": "無線滑鼠"}, "",
          {"en": "8K polling rate, 49g ultralight shell.",
           "zhHans": "8000Hz 回报率，49g 轻量化外壳。",
           "zhHant": "8000Hz 回報率，49g 輕量化外殼。"},
          24900, 29900, ["mouse", "wireless"], "mouse"),
        P(14, "Office Silent Mouse", {"en": "Silent Mouse", "zhHans": "静音鼠标", "zhHant": "靜音滑鼠"}, "",
          {"en": "Muted clicks that survive open offices.",
           "zhHans": "按键静音处理，开放办公室友好。",
           "zhHant": "按鍵靜音處理，開放辦公室友善。"},
          7900, 9900, ["mouse", "silent"], "mouse"),
        P(15, "View 27", {"en": "4K Monitor", "zhHans": "4K 显示器", "zhHant": "4K 顯示器"}, "27英寸",
          {"en": "Factory-calibrated color, Type-C 90W.",
           "zhHans": "出厂调色，Type-C 一线通 90W 反充。",
           "zhHant": "原廠調色，Type-C 一線通 90W 反充。"},
          219900, 259900, ["monitor", "4k"], "monitor"),
        P(15, "View Portable", {"en": "Portable Monitor", "zhHans": "便携显示器", "zhHant": "攜帶顯示器"}, "15.6英寸",
          {"en": "Magnetic cover stand, single-cable setup.",
           "zhHans": "磁吸保护套支架，一线即用。",
           "zhHant": "磁吸保護套支架，一線即用。"},
          99900, 119900, ["monitor", "portable"], "monitor"),
    ],
    3: [  # 家用电器
        P(16, "CycloVAC S9", {"en": "Robot Vacuum", "zhHans": "扫拖机器人", "zhHant": "掃拖機器人"}, "",
          {"en": "AI obstacle avoidance and self-emptying base.",
           "zhHans": "AI 避障+自动集尘，解放双手。",
           "zhHant": "AI 避障+自動集塵，解放雙手。"},
          289900, 359900, ["vacuum", "robot"], "vacuum", flash=True),
        P(16, "Wash X", {"en": "Wall-wash Robot", "zhHans": "洗地机器人", "zhHant": "洗地機器人"}, "",
          {"en": "Mops floors and cleans its own rollers.",
           "zhHans": "会拖地，还会自己搓滚刷。",
           "zhHant": "會拖地，還會自己搓滾刷。"},
          399900, 469900, ["vacuum", "mop"], "vacuum"),
        P(17, "AirFry 5L", {"en": "Air Fryer", "zhHans": "空气炸锅", "zhHant": "氣炸鍋"}, "5L",
          {"en": "Visual window, one-dial presets for crispy snacks.",
           "zhHans": "可视窗+旋钮预设，炸物零失败。",
           "zhHant": "視窗+旋鈕預設，炸物零失敗。"},
          29900, 39900, ["airfryer", "kitchen"], "air fryer"),
        P(17, "MultiPot 6L", {"en": "Pressure Cooker", "zhHans": "电压力锅", "zhHant": "電壓力鍋"}, "6L",
          {"en": "Eight-in-one cooking from stews to yogurt.",
           "zhHans": "炖煮焖焗一锅八用。",
           "zhHant": "燉煮燜燴一鍋八用。"},
          34900, 42900, ["cooker", "kitchen"], "rice cooker"),
        P(17, "RicePro", {"en": "Rice Cooker", "zhHans": "电饭煲", "zhHant": "電子鍋"}, "4L IH",
          {"en": "IH heating for fluffier grains every time.",
           "zhHans": "IH 电磁加热，粒粒分明。",
           "zhHant": "IH 電磁加熱，粒粒分明。"},
          49900, 59900, ["ricecooker", "kitchen"], "rice cooker"),
        P(18, "BrewBar Espresso", {"en": "Espresso Machine", "zhHans": "意式咖啡机", "zhHant": "義式咖啡機"}, "20bar",
          {"en": "20-bar pump and steam wand for cafe-level shots.",
           "zhHans": "20bar 泵+蒸汽奶泡棒，在家出品咖啡馆。",
           "zhHant": "20bar 泵+蒸氣奶泡棒，在家重現咖啡館。"},
          139900, 169900, ["coffee", "espresso"], "coffee machine"),
        P(18, "DripDaily", {"en": "Drip Coffee Maker", "zhHans": "滴滤咖啡机", "zhHant": "滴濾咖啡機"}, "",
          {"en": "Bean-to-cup grinder built in.",
           "zhHans": "自带磨豆，现磨现煮。",
           "zhHant": "自帶磨豆，現磨現煮。"},
          69900, 84900, ["coffee", "drip"], "coffee machine"),
        P(19, "PureAir Pro", {"en": "Air Purifier", "zhHans": "空气净化器", "zhHant": "空氣清淨機"}, "",
          {"en": "HEPA-13 filtration for 60㎡ rooms.",
           "zhHans": "HEPA-13 滤网，60㎡ 大空间适用。",
           "zhHant": "HEPA-13 濾網，60㎡ 大空間適用。"},
          129900, 159900, ["purifier", "hepa"], "air purifier"),
        P(19, "BreezeTower", {"en": "Bladeless Fan", "zhHans": "无叶风扇", "zhHant": "無葉風扇"}, "",
          {"en": "Quiet airflow that is safe around kids.",
           "zhHans": "无叶安全出风，带娃家庭放心。",
           "zhHant": "無葉安全出風，育兒家庭安心。"},
          79900, 99900, ["fan", "bladeless"], "fan"),
        P(20, "SteamCare", {"en": "Garment Steamer", "zhHans": "挂烫机", "zhHant": "掛燙機"}, "",
          {"en": "30-second heatup, kills dust mites on fabric.",
           "zhHans": "30 秒出蒸汽，除螨熨烫二合一。",
           "zhHant": "30 秒出蒸汽，除蟎熨燙二合一。"},
          29900, 36900, ["steamer", "laundry"], "iron"),
        P(20, "DryBox Mini", {"en": "Shoe Dryer", "zhHans": "烘鞋器", "zhHant": "烘鞋器"}, "",
          {"en": "Ozone deodorizing for rainy-day shoes.",
           "zhHans": "臭氧除味，雨天湿鞋 overnight 干爽。",
           "zhHant": "臭氧除味，雨天濕鞋一夜乾爽。"},
          12900, 15900, ["dryer", "shoes"], "iron"),
        P(21, "FrostFree 452", {"en": "Refrigerator", "zhHans": "冰箱", "zhHant": "冰箱"}, "452L 十字门",
          {"en": "Dual-cycle cooling keeps produce crisp longer.",
           "zhHans": "双循环制冷，果蔬保鲜更久。",
           "zhHant": "雙循環製冷，蔬果保鮮更久。"},
          329900, 379900, ["fridge", "large"], "refrigerator"),
    ],
    4: [  # 耳机影音
        P(0, "Pods Pro 3", {"en": "ANC Earbuds", "zhHans": "降噪耳机", "zhHant": "降噪耳機"}, "",
          {"en": "48dB hybrid ANC with spatial audio.",
           "zhHans": "48dB 混合降噪，支持空间音频。",
           "zhHant": "48dB 混合降噪，支援空間音訊。"},
          99900, 129900, ["anc", "earbuds"], "earbuds", flash=True),
        P(1, "ClipAir", {"en": "Open-ear Clip Earbuds", "zhHans": "耳夹式耳机", "zhHant": "耳夾式耳機"}, "",
          {"en": "2026's hottest form factor: open-ear, all-day comfort.",
           "zhHans": "年度爆火形态：耳夹开放佩戴，久戴不痛。",
           "zhHant": "年度爆紅形態：耳夾開放配戴，久戴不痛。"},
          49900, 59900, ["clip", "open-ear"], "earbuds", flash=True),
        P(1, "BoneRun", {"en": "Bone Conduction Headset", "zhHans": "骨传导耳机", "zhHant": "骨傳導耳機"}, "",
          {"en": "Stay aware of traffic while training.",
           "zhHans": "跑步骑行不堵耳，安全听见环境音。",
           "zhHant": "跑步騎行不堵耳，安心聽見環境音。"},
          39900, 49900, ["bone", "sports"], "headphones"),
        P(2, "Wire C", {"en": "USB-C Earphones", "zhHans": "Type-C 有线耳机", "zhHant": "Type-C 有線耳機"}, "",
          {"en": "The retro comeback: zero latency, zero charging.",
           "zhHans": "翻红单品：零延迟，不用充电。",
           "zhHant": "翻紅單品：零延遲，無需充電。"},
          5900, 7900, ["wired", "usbc"], "earphones"),
        P(3, "Studio 900", {"en": "Over-ear Headphones", "zhHans": "头戴式耳机", "zhHant": "頭戴式耳機"}, "",
          {"en": "50mm drivers tuned for long mixing sessions.",
           "zhHans": "50mm 单元，长时间监听也舒适。",
           "zhHant": "50mm 單元，長時間監聽也舒適。"},
          39900, 49900, ["over-ear", "studio"], "headphones"),
        P(4, "SilentMax", {"en": "Travel ANC Headphones", "zhHans": "旅行降噪头戴", "zhHant": "旅行降噪頭戴"}, "",
          {"en": "60h playtime, folds flat for the commute.",
           "zhHans": "60 小时续航，通勤折叠随行。",
           "zhHant": "60 小時續航，通勤摺疊隨行。"},
          89900, 109900, ["anc", "over-ear"], "headphones"),
        P(5, "Boom 360", {"en": "Bluetooth Speaker", "zhHans": "蓝牙音箱", "zhHant": "藍牙喇叭"}, "",
          {"en": "IP67 waterproof, pairs two for stereo.",
           "zhHans": "IP67 防水，可组双声道立体声。",
           "zhHant": "IP67 防水，可組雙聲道立體聲。"},
          34900, 42900, ["speaker", "bluetooth"], "speaker"),
        P(6, "VinylOne", {"en": "Turntable", "zhHans": "黑胶唱片机", "zhHant": "黑膠唱機"}, "",
          {"en": "Built-in preamp, Bluetooth out to your speakers.",
           "zhHans": "内置唱放，蓝牙直连音箱。",
           "zhHant": "內建唱放，藍牙直連喇叭。"},
          109900, 129900, ["vinyl", "turntable"], "turntable"),
        P(7, "Beam Projector", {"en": "Smart Projector", "zhHans": "智能投影仪", "zhHant": "智慧投影機"}, "",
          {"en": "Auto-focus 1080p native, 150-inch max.",
           "zhHans": "原生 1080P 自动对焦，最大 150 英寸。",
           "zhHant": "原生 1080P 自動對焦，最大 150 吋。"},
          249900, 299900, ["projector", "cinema"], "projector", flash=True),
        P(8, "SoundBar 2.1", {"en": "Soundbar", "zhHans": "回音壁音响", "zhHant": "Soundbar 音響"}, "",
          {"en": "Wireless subwoofer, night mode for apartments.",
           "zhHans": "无线低音炮，夜间模式不扰邻。",
           "zhHant": "無線超低音，夜間模式不擾鄰。"},
          99900, 129900, ["soundbar", "tv"], "speaker"),
    ],
    5: [  # 服饰鞋包
        P(9, "CloudDown 800", {"en": "Down Jacket", "zhHans": "羽绒服", "zhHant": "羽絨外套"}, "800蓬",
          {"en": "800-fill goose down, packs into its own pocket.",
           "zhHans": "800 蓬鹅绒，可收纳进口袋。",
           "zhHant": "800 蓬鵝絨，可收納進口袋。"},
          89900, 129900, ["downjacket", "winter"], "down jacket", flash=True),
        P(10, "Softshell City", {"en": "Softshell Jacket", "zhHans": "软壳外套", "zhHant": "軟殼外套"}, "",
          {"en": "Windproof, water-repellent, city-commute cut.",
           "zhHans": "防风泼水，通勤版型利落。",
           "zhHant": "防風撥水，通勤版型俐落。"},
          49900, 64900, ["jacket", "windbreaker"], "jacket"),
        P(11, "Merino Base", {"en": "Merino Baselayer", "zhHans": "美利奴保暖内衣", "zhHant": "美麗諾保暖衣"}, "",
          {"en": "17.5-micron merino, itch-free warmth.",
           "zhHans": "17.5 微支美利奴羊毛，亲肤不扎。",
           "zhHant": "17.5 微支美麗諾羊毛，親膚不扎。"},
          39900, 49900, ["merino", "baselayer"], "sweater"),
        P(12, "HeavyLoop Hoodie", {"en": "Heavyweight Hoodie", "zhHans": "重磅卫衣", "zhHant": "重磅衛衣"}, "450g",
          {"en": "450gsm loopback cotton, boxy street fit.",
           "zhHans": "450 克毛圈棉，宽松街头版型。",
           "zhHant": "450 克毛圈棉，寬鬆街頭版型。"},
          29900, 36900, ["hoodie", "streetwear"], "hoodie"),
        P(13, "AirRunner 4", {"en": "Running Shoes", "zhHans": "跑鞋", "zhHant": "跑鞋"}, "",
          {"en": "Supercritical foam returns 78% energy.",
           "zhHans": "超临界发泡中底，回弹 78%。",
           "zhHant": "超臨界發泡中底，回彈 78%。"},
          49900, 59900, ["running", "shoes"], "running shoes", flash=True),
        P(9, "TrailGrip GTX", {"en": "Trail Shoes", "zhHans": "越野跑鞋", "zhHant": "越野跑鞋"}, "",
          {"en": "Aggressive lugs bite into wet gravel.",
           "zhHans": "深齿抓地，湿滑碎石路稳住。",
           "zhHant": "深齒抓地，濕滑碎石路穩住。"},
          54900, 66900, ["trail", "shoes"], "hiking boots"),
        P(14, "BoardLeather Lo", {"en": "Leather Sneakers", "zhHans": "小白鞋", "zhHant": "小白鞋"}, "",
          {"en": "Full-grain leather, machine washable insole.",
           "zhHans": "头层牛皮鞋面，鞋垫可拆洗。",
           "zhHant": "頭層牛皮鞋面，鞋墊可拆洗。"},
          39900, 49900, ["sneakers", "white"], "sneakers"),
        P(15, "Chelsea 05", {"en": "Chelsea Boots", "zhHans": "切尔西靴", "zhHant": "切爾西靴"}, "",
          {"en": "Goodyear welted, resoleable for years.",
           "zhHans": "固特异工艺，穿旧可换底。",
           "zhHant": "固特異工藝，穿舊可換底。"},
          69900, 84900, ["boots", "chelsea"], "leather shoes"),
        P(16, "Everyday Pack 22L", {"en": "Backpack", "zhHans": "双肩包", "zhHant": "後背包"}, "22L",
          {"en": "16-inch laptop sleeve, luggage pass-through.",
           "zhHans": "可放 16 寸笔电，行李箱拉杆穿越设计。",
           "zhHant": "可放 16 吋筆電，行李箱拉桿穿越設計。"},
          34900, 42900, ["backpack", "commute"], "backpack"),
        P(16, "Tote Canvas", {"en": "Canvas Tote", "zhHans": "帆布托特包", "zhHant": "帆布托特包"}, "",
          {"en": "16oz canvas with leather-reinforced base.",
           "zhHans": "16 安厚帆布，皮革加固底托。",
           "zhHant": "16 安厚帆布，皮革加固底托。"},
          15900, 19900, ["tote", "canvas"], "bag"),
        P(17, "Metro Crossbody", {"en": "Crossbody Bag", "zhHans": "斜挎包", "zhHant": "斜背包"}, "",
          {"en": "RFID-blocking pocket and magnetic quick clasp.",
           "zhHans": "防盗刷卡位+磁吸快开扣。",
           "zhHant": "防盜刷卡位+磁吸快開扣。"},
          25900, 31900, ["crossbody", "bag"], "handbag"),
        P(18, "BaseCap Logo", {"en": "Baseball Cap", "zhHans": "棒球帽", "zhHant": "棒球帽"}, "",
          {"en": "Unstructured six-panel with adjustable strap.",
           "zhHans": "软顶六片，可调节头围。",
           "zhHant": "軟頂六片，可調節頭圍。"},
          8900, 11900, ["cap", "accessory"], "cap"),
        P(19, "SilkSquare 90", {"en": "Silk Scarf", "zhHans": "真丝方巾", "zhHant": "真絲方巾"}, "90cm",
          {"en": "90cm mulberry silk, hand-rolled edges.",
           "zhHans": "90cm 桑蚕丝，手工卷边。",
           "zhHant": "90cm 桑蠶絲，手工捲邊。"},
          29900, 39900, ["scarf", "silk"], "scarf"),
        P(20, "ThermalSet W", {"en": "Thermal Set", "zhHans": "德绒保暖套装", "zhHant": "德絨保暖套裝", }, "",
          {"en": "Brushed thermo-knit, seamless cuffs.",
           "zhHans": "德绒磨毛面料，无痕袖口。",
           "zhHant": "德絨磨毛面料，無痕袖口。"},
          19900, 25900, ["thermal", "winter"], "clothing"),
        P(21, "WideLeg Denim", {"en": "Wide-leg Jeans", "zhHans": "阔腿牛仔裤", "zhHant": "闊腿牛仔褲"}, "",
          {"en": "Rigid 13oz selvedge that breaks in beautifully.",
           "zhHans": "13oz 赤耳丹宁，越穿越有型。",
           "zhHant": "13oz 赤耳丹寧，越穿越有型。"},
          35900, 44900, ["jeans", "denim"], "jeans"),
        P(22, "LoungeKnit Set", {"en": "Loungewear Set", "zhHans": "家居服套装", "zhHant": "家居服套裝"}, "",
          {"en": "Modal blend, soft enough to sleep in.",
           "zhHans": "莫代尔混纺，软到可以直接睡。",
           "zhHant": "莫代爾混紡，軟到可以直接睡。"},
          17900, 22900, ["loungewear", "home"], "pajamas"),
    ],
    6: [  # 美妆个护
        P(23, "Glow Serum", {"en": "Brightening Serum", "zhHans": "美白精华", "zhHant": "美白精華"}, "30ml",
          {"en": "5% niacinamide with tranexamic acid.",
           "zhHans": "5% 烟酰胺+传明酸配方。",
           "zhHant": "5% 菸鹼醯胺+傳明酸配方。"},
          21900, 26900, ["serum", "skincare"], "skincare", flash=True),
        P(23, "Barrier Cream", {"en": "Moisturizer", "zhHans": "保湿面霜", "zhHant": "保濕面霜"}, "50g",
          {"en": "Ceramide complex repairs winter-dry skin.",
           "zhHans": "神经酰胺复配，拯救冬季干皮。",
           "zhHant": "神經醯胺複配，拯救冬季乾肌。"},
          18900, 22900, ["cream", "moisturizer"], "skincare"),
        P(24, "SunScreen SPF50+", {"en": "Sunscreen", "zhHans": "防晒霜", "zhHant": "防曬乳"}, "SPF50+ PA++++",
          {"en": "Watery gel finish, no white cast.",
           "zhHans": "水感啫喱质地，不假白不闷痘。",
           "zhHant": "水感凝膠質地，不假白不悶痘。"},
          12900, 15900, ["sunscreen", "spf"], "sunscreen"),
        P(24, "Cleansing Balm", {"en": "Cleansing Balm", "zhHans": "卸妆膏", "zhHant": "卸妝膏"}, "100ml",
          {"en": "Melts sunscreen and makeup in one pass.",
           "zhHans": "一瓶卸净防晒彩妆，乳化快不糊眼。",
           "zhHant": "一瓶卸淨防曬彩妝，乳化快不糊眼。"},
          10900, 13900, ["cleanser", "makeup-removal"], "cosmetics"),
        P(25, "Velvet Lip #08", {"en": "Matte Lipstick", "zhHans": "哑光唇膏", "zhHant": "霧面唇膏"}, "#08 枫叶红",
          {"en": "Weightless matte that never cracks.",
           "zhHans": "轻盈雾面，显白不拔干。",
           "zhHant": "輕盈霧面，顯白不拔乾。"},
          9900, 12900, ["lipstick", "makeup"], "lipstick"),
        P(25, "Gloss Water", {"en": "Lip Gloss", "zhHans": "镜面唇釉", "zhHant": "鏡面唇釉"}, "",
          {"en": "Mirror shine with a hint of mint.",
           "zhHans": "镜面水光，淡淡薄荷清凉感。",
           "zhHant": "鏡面水光，淡淡薄荷清涼感。"},
          8900, 10900, ["lipgloss", "makeup"], "lipstick"),
        P(26, "Palette Sunset", {"en": "Eyeshadow Palette", "zhHans": "眼影盘", "zhHant": "眼影盤"}, "12色",
          {"en": "Buttery mattes and foil shimmers.",
           "zhHans": "软糯哑光+金属偏光，一盘成妆。",
           "zhHant": "軟糯霧面+金屬偏光，一盤成妝。"},
          14900, 18900, ["eyeshadow", "palette"], "cosmetics"),
        P(26, "Liquid Blush", {"en": "Liquid Blush", "zhHans": "液体腮红", "zhHant": "液體腮紅"}, "",
          {"en": "One dot is enough for a natural flush.",
           "zhHans": "一点就晕染，自然好气色。",
           "zhHant": "一點就暈染，自然好氣色。"},
          8900, 10900, ["blush", "makeup"], "cosmetics"),
        P(27, "HairFix Bond", {"en": "Hair Mask", "zhHans": "发膜", "zhHant": "髮膜"}, "250ml",
          {"en": "Bond-repair treatment for bleached hair.",
           "zhHans": "漂染救星，修护二硫键。",
           "zhHant": "漂染救星，修護雙硫鍵。"},
          13900, 16900, ["haircare", "mask"], "shampoo"),
        P(27, "ScalpSerum", {"en": "Scalp Serum", "zhHans": "头皮精华", "zhHant": "頭皮精華"}, "",
          {"en": "Caffeine + peptides for fuller-looking hair.",
           "zhHans": "咖啡因+胜肽，蓬松感看得见。",
           "zhHant": "咖啡因+勝肽，蓬鬆感看得見。"},
          15900, 19900, ["scalp", "haircare"], "shampoo"),
        P(28, "Aqua Cologne", {"en": "Eau de Toilette", "zhHans": "淡香水", "zhHant": "淡香水"}, "50ml",
          {"en": "Bergamot and sea salt, clean and unisex.",
           "zhHans": "佛手柑与海盐，干净的中性香。",
           "zhHant": "佛手柑與海鹽，乾淨的中性香。"},
          29900, 36900, ["perfume", "fragrance"], "perfume"),
        P(28, "Oud Intense", {"en": "Eau de Parfum", "zhHans": "浓香水", "zhHant": "濃香水"}, "30ml",
          {"en": "Smoky oud with warm amber drydown.",
           "zhHans": "烟熏乌木，尾调琥珀温暖。",
           "zhHant": "煙燻烏木，尾調琥珀溫暖。"},
          39900, 49900, ["perfume", "oud"], "perfume"),
        P(29, "SonicBrush X", {"en": "Electric Toothbrush", "zhHans": "电动牙刷", "zhHant": "電動牙刷"}, "",
          {"en": "Pressure sensor guards your gums.",
           "zhHans": "压感提醒，刷牙不伤龈。",
           "zhHant": "壓感提醒，刷牙不傷齦。"},
          24900, 31900, ["toothbrush", "sonic"], "toothbrush"),
        P(29, "WaterFloss Pro", {"en": "Water Flosser", "zhHans": "冲牙器", "zhHant": "沖牙器"}, "",
          {"en": "180ml tank, five pressure modes.",
           "zhHans": "180ml 大水箱，五档水压。",
           "zhHant": "180ml 大水箱，五段水壓。"},
          19900, 25900, ["flosser", "oral"], "toothbrush"),
    ],
}
