# -*- coding: utf-8 -*-
# 分类7-12 商品数据（三语）
from products_data_a import P

PRODUCTS_B = {
    7: [  # 食品生鲜
        dict_snack := P(0, "", {"en": "Nut Gift Box", "zhHans": "每日坚果礼盒", "zhHant": "每日堅果禮盒"}, "30包",
          {"en": "Six nuts and dried fruits per pack, fresh-locked.",
           "zhHans": "六种坚果果干配比，锁鲜独立包。",
           "zhHant": "六種堅果果乾配比，鎖鮮獨立包。"},
          12900, 16900, ["nuts", "snack"], "nuts", flash=True),
        P(1, "", {"en": "Instant Noodles", "zhHans": "网红拌面", "zhHant": "網紅拌麵"}, "5连包",
          {"en": "Springy noodles with scallion-oil sauce.",
           "zhHans": "葱油酱汁+弹牙碱水面。",
           "zhHant": "蔥油醬汁+彈牙鹼水麵。"},
          3900, 4900, ["noodles", "instant"], "noodles"),
        P(2, "", {"en": "Coffee Beans", "zhHans": "精品咖啡豆", "zhHant": "精品咖啡豆"}, "1kg",
          {"en": "Medium roast blend, notes of chocolate and plum.",
           "zhHans": "中烘拼配，巧克力与乌梅风味。",
           "zhHant": "中烘拼配，巧克力與烏梅風味。"},
          15900, 19900, ["coffee", "beans"], "coffee beans"),
        P(3, "", {"en": "Milk Oolong", "zhHans": "金萱奶茶专用茶", "zhHant": "金萱奶茶專用茶"}, "",
          {"en": "Creamy oolong base for homemade milk tea.",
           "zhHans": "自带奶香的金萱，自制奶茶基底。",
           "zhHant": "自帶奶香的金萱，自製奶茶基底。"},
          6900, 8900, ["tea", "oolong"], "tea"),
        P(4, "", {"en": "Dried Mango", "zhHans": "芒果干", "zhHant": "芒果乾", }, "200g",
          {"en": "No added sugar, just sun-sweet fruit.",
           "zhHans": "零添加蔗糖，只有阳光的甜。",
           "zhHant": "零添加蔗糖，只有陽光的甜。"},
          4500, 5900, ["mango", "dried-fruit"], "dried fruit"),
        P(5, "", {"en": "Chili Crisp", "zhHans": "油泼辣子", "zhHant": "油潑辣子"}, "210g",
          {"en": "Crispy chili flakes in aromatic oil.",
           "zhHans": "香脆辣椒粒，拌饭拌面都香。",
           "zhHant": "香脆辣椒粒，拌飯拌麵都香。"},
          2900, 3600, ["chili", "sauce"], "sauce"),
        P(6, "", {"en": "Fresh Milk", "zhHans": "低温鲜牛奶", "zhHant": "低溫鮮乳" }, "950ml×2",
          {"en": "75°C pasteurized, creamy but clean finish.",
           "zhHans": "75°C 巴氏杀菌，奶香浓而不腻。",
           "zhHant": "75°C 巴氏殺菌，奶香濃而不膩。"},
          3900, 4500, ["milk", "fresh"], "milk"),
        P(7, "", {"en": "Greek Yogurt", "zhHans": "希腊酸奶", "zhHant": "希臘優格"}, "4杯",
          {"en": "Triple strained, thick as cheesecake.",
           "zhHans": "三次过滤，浓稠如芝士蛋糕。",
           "zhHant": "三次過濾，濃稠如起司蛋糕。"},
          4900, 5900, ["yogurt", "dairy"], "yogurt"),
        P(8, "", {"en": "Atlantic Salmon", "zhHans": "冰鲜三文鱼刺身段", "zhHant": "冰鮮鮭魚生魚片段"}, "400g",
          {"en": "Sushi-grade cut, cold-chain delivered.",
           "zhHans": "刺身级部位，冷链直达。",
           "zhHant": "生魚片級部位，冷鏈直達。"},
          8900, 10900, ["salmon", "seafood"], "salmon"),
        P(9, "", {"en": "Beef Cube", "zhHans": "原切牛腱子", "zhHant": "原切牛腱子"}, "1kg",
          {"en": "Single-origin grass-fed, no marinade injected.",
           "zhHans": "草饲整切，无注水无腌制。",
           "zhHant": "草飼整切，無注水無醃製。"},
          13900, 16900, ["beef", "meat"], "steak"),
        P(10, "", {"en": "Cherry Box", "zhHans": "车厘子礼盒", "zhHant": "櫻桃禮盒"}, "2J 500g",
          {"en": "Crisp sweet cherries in foam-protected box.",
           "zhHans": "脆甜多汁，防震泡沫箱锁鲜。",
           "zhHant": "脆甜多汁，防震保麗龍箱鎖鮮。"},
          9990, 13900, ["cherry", "fruit"], "cherries", flash=True),
        P(11, "", {"en": "Aiyu Jelly Kit", "zhHans": "爱玉冻DIY套装", "zhHant": "愛玉凍DIY套裝"}, "",
          {"en": "Summer dessert kit with lemon syrup.",
           "zhHans": "夏日消暑甜品，配柠檬糖浆。",
           "zhHant": "夏日消暑甜品，配檸檬糖漿。"},
          3500, 4500, ["jelly", "dessert"], "dessert"),
        P(12, "", {"en": "Granola", "zhHans": "烘焙麦片", "zhHant": "烘焙穀物麥片"}, "500g",
          {"en": "Oat clusters baked with honey and coconut.",
           "zhHans": "蜂蜜椰子烘烤，块块酥脆。",
           "zhHant": "蜂蜜椰子烘烤，塊塊酥脆。"},
          4900, 6200, ["granola", "breakfast"], "cereal"),
        P(13, "", {"en": "Seaweed Snack", "zhHans": "海苔脆片", "zhHant": "海苔脆片"}, "",
          {"en": "Roasted with sesame oil, lightly salted.",
           "zhHans": "芝麻油轻焙，薄脆不腻口。",
           "zhHant": "芝麻油輕焙，薄脆不膩口。"},
          2500, 3200, ["seaweed", "snack"], "snacks"),
    ],
    8: [  # 家居日用
        P(14, "CloudLoft Pillow", {"en": "Bed Pillow", "zhHans": "云感枕头", "zhHant": "雲感枕頭"}, "一对",
          {"en": "Adjustable fill height for side and back sleepers.",
           "zhHans": "枕高可调，侧睡仰睡都贴合。",
           "zhHant": "枕高可調，側睡仰睡都貼合。"},
          19900, 25900, ["pillow", "bedding"], "pillow"),
        P(14, "TENCEL Set", {"en": "Bedding Set", "zhHans": "天丝四件套", "zhHant": "天絲床包組"}, "1.8m床",
          {"en": "Cool-touch tencel, deep-pocket fitted sheet.",
           "zhHans": "凉感天丝，深口袋床笠不移位。",
           "zhHant": "涼感天絲，深口袋床包不移位。"},
          39900, 49900, ["bedding", "tencel"], "bedding", flash=True),
        P(15, "SoyGlow Candle", {"en": "Scented Candle", "zhHans": "香薰蜡烛", "zhHant": "香氛蠟燭"}, "180g",
          {"en": "Soy wax with fig and cedar notes.",
           "zhHans": "大豆蜡，无花果与雪松调。",
           "zhHant": "大豆蠟，無花果與雪松調。"},
          9900, 12900, ["candle", "aroma"], "candle"),
        P(15, "ReedDiffuser", {"en": "Reed Diffuser", "zhHans": "无火藤条香薰", "zhHant": "無火藤條香薰"}, "150ml",
          {"en": "Eight-week continuous scent for entryways.",
           "zhHans": "持续留香约八周，玄关卧室适用。",
           "zhHant": "持續留香約八週，玄關臥室適用。"},
          11900, 14900, ["diffuser", "aroma"], "perfume"),
        P(16, "Umbrella Auto", {"en": "Automatic Umbrella", "zhHans": "自动晴雨伞", "zhHant": "自動晴雨傘"}, "",
          {"en": "Ten-bone fiberglass frame survives gales.",
           "zhHans": "十骨玻纤抗风，一键开收。",
           "zhHant": "十骨玻纖抗風，一鍵開收。"},
          7900, 9900, ["umbrella", "rain"], "umbrella"),
        P(17, "ThermoFlask 1L", {"en": "Insulated Bottle", "zhHans": "保温杯", "zhHant": "保溫瓶"}, "1L",
          {"en": "24h heat retention, leak-proof lid.",
           "zhHans": "24 小时保温，倒置不漏。",
           "zhHant": "24 小時保溫，倒置不漏。"},
          12900, 15900, ["bottle", "thermal"], "water bottle"),
        P(18, "DustFree Mop", {"en": "Flat Spray Mop", "zhHans": "喷水平板拖把", "zhHant": "噴水平板拖把"}, "",
          {"en": "360° swivel head with washable pads.",
           "zhHans": "360° 旋转头，拖布可洗可换。",
           "zhHant": "360° 旋轉頭，拖布可洗可換。"},
          8900, 11900, ["mop", "cleaning"], "cleaning"),
        P(18, "Vac Bags XL", {"en": "Vacuum Storage Bags", "zhHans": "真空压缩袋", "zhHant": "真空壓縮袋"}, "6只装",
          {"en": "Triple winter coats down to one drawer.",
           "zhHans": "三件冬被压缩成一抽屉。",
           "zhHant": "三件冬被壓縮成一抽屜。"},
          5900, 7900, ["storage", "vacuum"], "storage"),
        P(19, "LED Mirror", {"en": "Vanity Mirror", "zhHans": "化妆镜", "zhHant": "化妝鏡"}, "",
          {"en": "Three color temperatures, USB-C powered.",
           "zhHans": "三档色温，Type-C 供电。",
           "zhHant": "三段色溫，Type-C 供電。"},
          14900, 18900, ["mirror", "vanity"], "mirror"),
        P(20, "Laundry Balls", {"en": "Washer Balls", "zhHans": "洗衣球", "zhHant": "洗衣球"}, "",
          {"en": "Reduces tangling and residue without detergent boosters.",
           "zhHans": "减少缠绕残留，无需额外柔顺剂。",
           "zhHant": "減少纏繞殘留，無需額外柔順劑。"},
          3900, 4900, ["laundry", "washing"], "laundry"),
        P(21, "Desk Organizer", {"en": "Desk Organizer", "zhHans": "桌面收纳架", "zhHant": "桌面收納架"}, "",
          {"en": "Bamboo and steel, tablet stand built in.",
           "zhHans": "竹木拼接，自带平板支架位。",
           "zhHant": "竹木拼接，自帶平板支架位。"},
          8900, 10900, ["organizer", "desk"], "desk"),
        P(22, "Blackout Curtain", {"en": "Blackout Curtains", "zhHans": "遮光窗帘", "zhHant": "遮光窗簾"}, "",
          {"en": "99% blackout with thermal lining.",
           "zhHans": "遮光率 99%，附带保温涂层。",
           "zhHant": "遮光率 99%，附帶保溫塗層。"},
          22900, 28900, ["curtain", "blackout"], "curtain"),
        P(23, "Slipper Cloud", {"en": "House Slippers", "zhHans": "棉拖鞋", "zhHant": "棉拖鞋"}, "",
          {"en": "Memory foam footbed, machine-washable.",
           "zhHans": "记忆鞋底，可直接机洗。",
           "zhHant": "記憶鞋底，可直接機洗。"},
          6900, 8900, ["slippers", "home"], "slippers"),
        P(24, "Storage Rack", {"en": "Shoe Rack", "zhHans": "落地鞋架", "zhHant": "落地鞋架"}, "6层",
          {"en": "Six tiers of breathable mesh shelving.",
           "zhHans": "六层网布层架，组装免工具。",
           "zhHant": "六層網布層架，組裝免工具。"},
          10900, 13900, ["rack", "shoes"], "shelf"),
    ],
    9: [  # 运动户外
        P(25, "IronBell Set", {"en": "Adjustable Dumbbell", "zhHans": "可调节哑铃", "zhHant": "可調節啞鈴"}, "24kg",
          {"en": "Dial from 2.5kg to 24kg in seconds.",
           "zhHans": "旋钮秒切 2.5-24kg。",
           "zhHant": "旋鈕秒切 2.5-24kg。"},
          89900, 109900, ["dumbbell", "fitness"], "dumbbell"),
        P(25, "YogaMat Pro", {"en": "Yoga Mat", "zhHans": "瑜伽垫", "zhHant": "瑜珈墊"}, "8mm",
          {"en": "Non-slip TPE with alignment lines.",
           "zhHans": "TPE 防滑带对位线。",
           "zhHant": "TPE 防滑帶對位線。"},
          15900, 19900, ["yoga", "mat"], "yoga mat"),
        P(26, "RowFlow", {"en": "Rowing Machine", "zhHans": "划船机", "zhHant": "划船機"}, "",
          {"en": "Water-resistance rower with app courses.",
           "zhHans": "水阻划船机，App 课程跟练。",
           "zhHant": "水阻划船機，App 課程跟練。"},
          199900, 249900, ["rowing", "cardio"], "gym"),
        P(26, "FoldTread", {"en": "Walking Pad", "zhHans": "走步机", "zhHant": "走路機"}, "",
          {"en": "Slides under the sofa, remote controlled.",
           "zhHans": "可推入沙发底，遥控操作。",
           "zhHant": "可推入沙發底，遙控操作。"},
          139900, 169900, ["treadmill", "walking"], "treadmill"),
        P(27, "CampTent 3", {"en": "Camping Tent", "zhHans": "露营帐篷", "zhHant": "露營帳篷"}, "3人",
          {"en": "Auto-pop-up setup under two minutes.",
           "zhHans": "两分钟自动速开。",
           "zhHant": "兩分鐘自動速開。"},
          45900, 55900, ["tent", "camping"], "tent"),
        P(27, "SleepPad R", {"en": "Sleeping Pad", "zhHans": "充气睡垫", "zhHant": "充氣睡墊"}, "",
          {"en": "R-value 4.5 for three-season nights.",
           "zhHans": "R 值 4.5，三季露营够暖。",
           "zhHant": "R 值 4.5，三季露營夠暖。"},
          29900, 36900, ["pad", "camping"], "camping"),
        P(28, "SummitPack 40L", {"en": "Hiking Backpack", "zhHans": "登山包", "zhHant": "登山包"}, "40L",
          {"en": "Ventilated frame and rain cover included.",
           "zhHans": "透气背架，附赠防雨罩。",
           "zhHant": "透氣背架，附贈防雨罩。"},
          49900, 59900, ["backpack", "hiking"], "backpack"),
        P(29, "TrailPole C", {"en": "Trekking Poles", "zhHans": "登山杖", "zhHant": "登山杖"}, "一对",
          {"en": "Carbon shafts with cork grips, 210g each.",
           "zhHans": "碳素杖身+软木握柄，单支仅 210g。",
           "zhHant": "碳素杖身+軟木握柄，單支僅 210g。"},
          35900, 42900, ["poles", "trekking"], "hiking"),
        P(30, "RideHelmet", {"en": "Bike Helmet", "zhHans": "骑行头盔", "zhHant": "安全帽"}, "",
          {"en": "In-mold shell, 24 vents, 280g.",
           "zhHans": "一体成型 24 孔通风，仅 280g。",
           "zhHant": "一體成型 24 孔通風，僅 280g。"},
          24900, 29900, ["helmet", "cycling"], "bicycle helmet"),
        P(31, "JumpRope S", {"en": "Smart Jump Rope", "zhHans": "智能跳绳", "zhHant": "智能跳繩"}, "",
          {"en": "Counts jumps and syncs workouts to your phone.",
           "zhHans": "自动计数，训练数据同步手机。",
           "zhHant": "自動計數，訓練數據同步手機。"},
          9900, 12900, ["rope", "jumping"], "jump rope"),
        P(31, "GripTrainer", {"en": "Grip Trainer", "zhHans": "握力器", "zhHant": "握力器"}, "",
          {"en": "Adjustable 10-60kg resistance.",
           "zhHans": "10-60kg 可调阻力。",
           "zhHant": "10-60kg 可調阻力。"},
          4900, 6900, ["grip", "training"], "fitness"),
        P(32, "PoolGoggles", {"en": "Swim Goggles", "zhHans": "泳镜", "zhHant": "泳鏡"}, "",
          {"en": "Anti-fog coating that lasts seasons.",
           "zhHans": "长效防雾镀膜，不起雾不勒眼。",
           "zhHant": "長效防霧鍍膜，不起霧不勒眼。"},
          7900, 9900, ["goggles", "swimming"], "swimming"),
    ],
    10: [  # 母婴玩具
        P(0, "Stroller Air", {"en": "Lightweight Stroller", "zhHans": "婴儿推车", "zhHant": "嬰兒推車"}, "",
          {"en": "6.2kg cabin-size fold with one hand.",
           "zhHans": "仅 6.2kg，单手折叠可登机。",
           "zhHant": "僅 6.2kg，單手摺疊可登機。"},
          129900, 159900, ["stroller", "baby"], "stroller"),
        P(1, "CozyCrib Sheet", {"en": "Crib Sheet", "zhHans": "婴儿床包", "zhHant": "嬰兒床包"}, "",
          {"en": "Organic cotton, OEKO-TEX certified.",
           "zhHans": "有机棉材质，OEKO-TEX 认证。",
           "zhHant": "有機棉材質，OEKO-TEX 認證。"},
          12900, 15900, ["crib", "bedding"], "baby"),
        P(2, "MilkWarmer", {"en": "Bottle Warmer", "zhHans": "温奶器", "zhHant": "溫奶器"}, "",
          {"en": "Precise 37°C warming without hot spots.",
           "zhHans": "精准 37°C，受热均匀不烫口。",
           "zhHant": "精準 37°C，受熱均勻不燙口。"},
          15900, 19900, ["warmer", "feeding"], "kitchen"),
        P(3, "SterilBox", {"en": "Bottle Sterilizer", "zhHans": "消毒烘干锅", "zhHant": "消毒烘乾鍋"}, "",
          {"en": "UV sterilize plus dry in 19 minutes.",
           "zhHans": "紫外线消毒+烘干，19 分钟搞定。",
           "zhHant": "紫外線消毒+烘乾，19 分鐘搞定。"},
          29900, 35900, ["sterilizer", "uv"], "appliance"),
        P(4, "DiaperBag Pro", {"en": "Diaper Backpack", "zhHans": "妈咪包", "zhHant": "媽咪包"}, "",
          {"en": "Insulated bottle pockets and changing pad.",
           "zhHans": "保温奶瓶位+便携尿布垫。",
           "zhHant": "保溫奶瓶位+便攜尿布墊。"},
          25900, 31900, ["diaperbag", "mom"], "backpack"),
        P(5, "BlockSet 120", {"en": "Building Blocks", "zhHans": "大颗粒积木", "zhHant": "大顆粒積木"}, "120粒",
          {"en": "Chunky toddler-safe bricks with storage bin.",
           "zhHans": "加厚大颗粒防误吞，附收纳桶。",
           "zhHant": "加厚大顆粒防誤吞，附收納桶。"},
          15900, 19900, ["blocks", "toys"], "toy blocks"),
        P(6, "PlushBear 40", {"en": "Teddy Bear", "zhHans": "毛绒泰迪熊", "zhHant": "毛絨泰迪熊"}, "40cm",
          {"en": "Hypoallergenic plush, embroidered eyes.",
           "zhHans": "低敏面料，刺绣眼睛更安全。",
           "zhHant": "低敏面料，刺繡眼睛更安全。"},
          9900, 12900, ["plush", "bear"], "teddy bear", flash=True),
        P(7, "PuzzleBoard", {"en": "Wooden Puzzle", "zhHans": "木质拼图", "zhHant": "木質拼圖", }, "",
          {"en": "Thick wooden pieces for little hands.",
           "zhHans": "加厚木质抓握片，锻炼精细动作。",
           "zhHant": "加厚木質抓握片，鍛鍊精細動作。"},
          6900, 8900, ["puzzle", "wooden"], "puzzle"),
        P(8, "RCDrift Mini", {"en": "RC Drift Car", "zhHans": "遥控漂移车", "zhHant": "遙控漂移車"}, "",
          {"en": "Four-wheel drive with swap drift tires.",
           "zhHans": "四轮驱动，漂移胎可换。",
           "zhHant": "四輪驅動，漂移胎可換。"},
          19900, 24900, ["rc", "car"], "toy car"),
        P(9, "ScienceKit Volcano", {"en": "STEM Science Kit", "zhHans": "STEM科学实验套装", "zhHant": "STEM科學實驗套裝"}, "",
          {"en": "Twenty safe experiments with illustrated manual.",
           "zhHans": "20 个安全小实验，图解说明书。",
           "zhHant": "20 個安全小實驗，圖解說明書。"},
          12900, 16900, ["stem", "science"], "science"),
        P(10, "KidsScooter", {"en": "Kick Scooter", "zhHans": "儿童滑板车", "zhHant": "兒童滑板車"}, "",
          {"en": "Lean-to-steer with glow wheels.",
           "zhHans": "重心转向+发光轮。",
           "zhHant": "重心轉向+發光輪。"},
          22900, 28900, ["scooter", "kids"], "scooter"),
        P(11, "BabyMonitor 2K", {"en": "Baby Monitor", "zhHans": "婴儿监护器", "zhHant": "嬰兒監視器"}, "",
          {"en": "2K night vision with cry alerts.",
           "zhHans": "2K 夜视，哭声即时提醒。",
           "zhHant": "2K 夜視，哭聲即時提醒。"},
          44900, 54900, ["monitor", "baby"], "camera"),
    ],
    11: [  # 图书文娱
        P(12, "", {"en": "Novel: Night Ferry", "zhHans": "小说《夜航渡》", "zhHant": "小說《夜航渡》"}, "",
          {"en": "Award-winning mystery set on a coastal line.",
           "zhHans": "获奖悬疑长篇，海岸线上的迷案。",
           "zhHant": "獲獎懸疑長篇，海岸線上的迷案。"},
          5900, 6900, ["novel", "mystery"], "book"),
        P(13, "", {"en": "Finance Basics", "zhHans": "理财入门书", "zhHant": "理財入門書"}, "",
          {"en": "Plain-language guide to compounding and ETFs.",
           "zhHans": "大白话讲透复利与指数投资。",
           "zhHant": "大白話講透複利與指數投資。"},
          4900, 5900, ["finance", "book"], "book"),
        P(14, "", {"en": "Parenting Handbook", "zhHans": "正面管教手册", "zhHant": "正向教養手冊"}, "",
          {"en": "Age-by-age scripts for calm parenting.",
           "zhHans": "分龄沟通脚本，温和而坚定。",
           "zhHant": "分齡溝通腳本，溫和而堅定。"},
          5500, 6600, ["parenting", "book"], "books"),
        P(15, "", {"en": "Art Calendar 2026", "zhHans": "2026艺术日历", "zhHant": "2026藝術日曆"}, "",
          {"en": "365 museum-grade prints on your desk.",
           "zhHans": "365 张馆藏级画作，桌面美术馆。",
           "zhHant": "365 張館藏級畫作，桌面美術館。"},
          8900, 11900, ["calendar", "art"], "art"),
        P(16, "", {"en": "Sketchbook A5", "zhHans": "素描本", "zhHant": "素描本"}, "",
          {"en": "160gsm paper handles light watercolor.",
           "zhHans": "160g 加厚纸面，可承受淡彩。",
           "zhHant": "160g 加厚紙面，可承受淡彩。"},
          3900, 4900, ["sketchbook", "drawing"], "notebook"),
        P(17, "", {"en": "Fountain Pen F", "zhHans": "钢笔 F尖", "zhHant": "鋼筆 F尖"}, "F尖",
          {"en": "Brass body that ages into your grip.",
           "zhHans": "黄铜笔身，越用越顺手。",
           "zhHant": "黃銅筆身，越用越順手。"},
          12900, 15900, ["pen", "fountain"], "fountain pen"),
        P(18, "", {"en": "Deck Poker Premium", "zhHans": "花切扑克牌", "zhHant": "花切撲克牌"}, "",
          {"en": "Air-cushion finish for smooth fans.",
           "zhHans": "气垫纹纸面，展牌顺滑。",
           "zhHant": "氣墊紋紙面，展牌順滑。"},
          4900, 5900, ["cards", "poker"], "playing cards"),
        P(19, "", {"en": "Go Board Set", "zhHans": "围棋套装", "zhHant": "圍棋套裝"}, "",
          {"en": "Bamboo board with double-convex stones.",
           "zhHans": "竹制棋盘+双凸棋子。",
           "zhHant": "竹製棋盤+雙凸棋子。"},
          15900, 19900, ["go", "boardgame"], "board game"),
        P(20, "", {"en": "Party Card Game", "zhHans": "聚会桌游卡牌", "zhHant": "聚會桌遊卡牌"}, "",
          {"en": "Five-minute rules, endless laughs.",
           "zhHans": "五分钟上手，笑点密度超标。",
           "zhHant": "五分鐘上手，笑點密度超標。"},
          6900, 8900, ["party", "boardgame"], "board game", flash=True),
        P(21, "", {"en": "Model Ship Kit", "zhHans": "木质帆船模型", "zhHant": "木質帆船模型"}, "",
          {"en": "Laser-cut parts, weekend build project.",
           "zhHans": "激光切割零件，周末手工首选。",
           "zhHant": "雷射切割零件，週末手工首選。"},
          19900, 24900, ["model", "craft"], "model ship"),
        P(22, "", {"en": "Vinyl Record: City Lights", "zhHans": "黑胶唱片《城市灯火》", "zhHant": "黑膠唱片《城市燈火》"}, "",
          {"en": "180g pressing of the indie classic.",
           "zhHans": "独立经典 180g 重磅压盘。",
           "zhHant": "獨立經典 180g 重磅壓盤。"},
          15900, 18900, ["vinyl", "music"], "vinyl record"),
        P(23, "", {"en": "Calligraphy Copybook", "zhHans": "字帖临摹套装", "zhHant": "字帖臨摹套裝"}, "",
          {"en": "Reusable grooved pages with pen included.",
           "zhHans": "凹槽字模可反复写，附赠钢笔。",
           "zhHant": "凹槽字模可反覆寫，附贈鋼筆。"},
          5900, 7900, ["calligraphy", "copybook"], "notebook"),
    ],
    12: [  # 宠物生活
        P(24, "CatTower XXL", {"en": "Cat Tree", "zhHans": "猫爬架", "zhHant": "貓跳台"}, "",
          {"en": "Multi-level condo with sisal posts.",
           "zhHans": "多层平台+剑麻猫抓柱。",
           "zhHant": "多層平台+劍麻貓抓柱。"},
          29900, 36900, ["cattree", "cat"], "cat tree"),
        P(25, "LitterRobot Lite", {"en": "Self-cleaning Litter Box", "zhHans": "自动猫砂盆", "zhHant": "自動貓砂盆"}, "",
          {"en": "Auto-sifts waste into a sealed drawer.",
           "zhHans": "自动分离排泄物，密封集便抽屉。",
           "zhHant": "自動分離排泄物，密封集便抽屜。"},
          129900, 159900, ["litterbox", "smart"], "cat"),
        P(26, "DogFood Salmon", {"en": "Salmon Dog Food", "zhHans": "三文鱼狗粮", "zhHant": "鮭魚狗糧"}, "7.5kg",
          {"en": "Grain-free formula for shiny coats.",
           "zhHans": "无谷配方，吃出亮毛发。",
           "zhHant": "無穀配方，吃出亮毛髮。"},
          34900, 42900, ["dogfood", "salmon"], "dog food"),
        P(27, "CatFood Tuna", {"en": "Tuna Cat Food", "zhHans": "金枪鱼猫罐头", "zhHant": "鮪魚貓罐頭"}, "12罐",
          {"en": "Human-grade chunks in natural broth.",
           "zhHans": "人食用级大肉块，原汤慢炖。",
           "zhHant": "人食用級大肉塊，原湯慢燉。"},
          12900, 15900, ["catfood", "canned"], "cat food"),
        P(28, "PetFountain 2L", {"en": "Pet Water Fountain", "zhHans": "宠物饮水机", "zhHant": "寵物飲水機"}, "",
          {"en": "Ultra-quiet pump encourages drinking.",
           "zhHans": "超静音水泵，主子更爱喝水。",
           "zhHant": "超靜音水泵，主子更愛喝水。"},
          15900, 19900, ["fountain", "pet"], "pet fountain"),
        P(29, "DogLeash Reflect", {"en": "Reflective Leash", "zhHans": "反光牵引绳", "zhHant": "反光牽引繩"}, "",
          {"en": "Shock-absorbing bungee for pullers.",
           "zhHans": "缓冲弹力段，爆冲也温柔。",
           "zhHant": "緩衝彈力段，暴衝也溫柔。"},
          6900, 8900, ["leash", "dog"], "dog leash"),
        P(30, "CatnipFish", {"en": "Catnip Toys", "zhHans": "木天蓼玩具", "zhHant": "木天薊玩具"}, "3只装",
          {"en": "Natural catnip-stuffed fish trio.",
           "zhHans": "天然木天蓼填充，三条装。",
           "zhHant": "天然木天薊填充，三條裝。"},
          3900, 4900, ["toy", "cat"], "cat toy"),
        P(31, "PetBed Oval", {"en": "Calming Pet Bed", "zhHans": "安抚宠物窝", "zhHant": "安撫寵物窩"}, "",
          {"en": "Raised rim supports head, washable cover.",
           "zhHans": "环形护头设计，外套可拆洗。",
           "zhHant": "環形護頭設計，外套可拆洗。"},
          12900, 16900, ["bed", "pet"], "dog bed", flash=True),
    ],
}
